services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: popcorn-palace
      POSTGRES_PASSWORD: popcorn-palace
      POSTGRES_DB: popcorn-palace
    ports:
      - target: 5432
        published: 5433 # change the port if 5432 is already in use. make sure to update the .env file
        protocol: tcp
  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: popcorn-palace
      POSTGRES_PASSWORD: popcorn-palace
      POSTGRES_DB: popcorn-palace-test
    ports:
      - target: 5432
        published: 5434 # change the port if 5433 is already in use. make sure to update the .env.test file
        protocol: tcp